user_input1 = input("Give me a noun. ")
user_input2 = input("Name a place. ")
user_input3 = input("Write an explanation. (Start with 'to') ")
user_input4 = input("Give me an action verb. ")
user_input5 = input("Give me another action verb. ")
user_input6 = input("Name an abstract idea. ")
user_input7 = input("Give me a superlative. ")
user_input8 = input("What's an object you use everyday? ")
user_input9 = input("Name an emotion. ")
user_input10 = input("Type the name of your favorite character. ")
user_input11 = input("Give me an action verb. ")
user_input12 = input("Give me a store name. ")
user_input13 = input("What would you say to comfort somebody? ")
print("This is a soliloquy by the famous " + user_input1 + " who journeyed to " + user_input2 + " " + user_input3 + ".")
print("I " + user_input4 + " over hills and " + user_input5 + " under bridges to figure out how to find " + user_input6 + " and to discover the " + user_input7 + " " + user_input8 + " in the universe.")
print("I was feeling " + user_input9 + " because my best friend " + user_input10 + " refused to accompany me and instead chose to " + user_input11 + ".") 
print("After he saw my " + user_input9 + " state, the vendor at " + user_input12 + " gave me a hug and said, " + user_input13 + ".")
print("I realized that the " + user_input12 + " worker was a better friend than " + user_input10 + " had ever been to me.")